### ISSUE TITLE
`lacosmicx` vs newer implementations

### ISSUE THREAD

**Issue by BSGalvan** [ivastar/grizli#19]
The docs mention installing [`lacosmicx`](https://github.com/cmccully/lacosmicx) if one wants to identify and remove cosmic rays from images.
However this package hasn't seen updates [since 2015](https://github.com/cmccully/lacosmicx/commits/master), and more importantly, is also not on PyPI.

In trying to look for alternatives, I was led to the following:

- [`lacosmic`](https://github.com/larrybradley/lacosmic), which is on PyPI and also seems to be [updated now and then](https://github.com/larrybradley/lacosmic/graphs/code-frequency). Curiously, the author [points towards](https://github.com/larrybradley/lacosmic/issues/7#issuecomment-770025155) the next package on this list.
- [`astroscrappy`](https://github.com/astropy/astroscrappy), which is an astropy affiliated package. Additionally, the current maintainer is the same person as for `lacosmicx`. There is a slight caveat here that in order to gain in speed, some changes have been made to the implementation of the original LA Cosmic algorithm (see the [Notes](https://github.com/astropy/astroscrappy#notes) for more information), which means we may have to test extra carefully if we are to adopt this package over `lacosmicx`.

**Comment by jdavies-st** [comment]
`astroscrappy` is the same package as `lacosmicx`, just maintained.  We should swap out `lacosmicx` for that.  👍

**Comment by jdavies-st** [comment]
Resolved by #22
