### ISSUE TITLE
Current pip install 

### ISSUE THREAD

**Issue by ivastar** [ivastar/grizli#4]
(ahw2022) momcheva@mac-n-152 ~ % pip install grizli
Collecting grizli
  Downloading grizli-1.6.0.tar.gz (13.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 17.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy
  Downloading numpy-1.23.4-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 18.5 MB/s eta 0:00:00
Collecting cython
  Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.3/986.3 kB 14.0 MB/s eta 0:00:00
Collecting astropy
  Using cached astropy-5.1-cp310-cp310-macosx_10_9_x86_64.whl (6.9 MB)
Collecting sregion>=1.0
  Using cached sregion-1.0.tar.gz (9.5 kB)
  Preparing metadata (setup.py) ... done
Collecting mastquery>=1.4
  Using cached mastquery-1.4.tar.gz (301 kB)
  Preparing metadata (setup.py) ... done
Collecting shapely
  Downloading Shapely-1.8.5.post1-cp310-cp310-macosx_10_9_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 13.7 MB/s eta 0:00:00
Collecting descartes
  Downloading descartes-1.1.0-py3-none-any.whl (5.8 kB)
Collecting pyerfa>=2.0
  Using cached pyerfa-2.0.0.1-cp310-cp310-macosx_10_9_x86_64.whl (340 kB)
Collecting PyYAML>=3.13
  Using cached PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl (197 kB)
Collecting packaging>=19.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting matplotlib
  Downloading matplotlib-3.6.1-cp310-cp310-macosx_10_12_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 17.8 MB/s eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.5-cp310-cp310-macosx_10_9_x86_64.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.1/241.1 kB 5.4 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp310-cp310-macosx_10_9_x86_64.whl (65 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-9.2.0-cp310-cp310-macosx_10_10_x86_64.whl (3.1 MB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.37.4-py3-none-any.whl (960 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 960.8/960.8 kB 13.6 MB/s eta 0:00:00
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: grizli, mastquery, sregion
  Building wheel for grizli (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [152 lines of output]
      C extension: .c
      /Users/momcheva/miniconda3/envs/ahw2022/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /Users/momcheva/miniconda3/envs/ahw2022/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
        warnings.warn(
      /Users/momcheva/miniconda3/envs/ahw2022/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'show-response' will not be supported in future versions. Please use the underscore name 'show_response' instead
        warnings.warn(
      /Users/momcheva/miniconda3/envs/ahw2022/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'astropy-package-template-example' will not be supported in future versions. Please use the underscore name 'astropy_package_template_example' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-x86_64-cpython-310
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/catalog.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/jwst_utils.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/version.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/combine.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/multifit.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/fake_image.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/model.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/prep.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/utils.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/grismconf.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/stack.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/fitting.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      copying grizli/ds9.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/run_MPI.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/photoz.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/reprocess.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/summary.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/default_params.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      copying grizli/pipeline/auto_script.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/pipeline
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/utils_c
      copying grizli/utils_c/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/utils_c
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_grismconf.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_utils.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_fits.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_jwst.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_cutils.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      copying grizli/tests/test_autoscript.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/tests
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      copying grizli/galfit/gfutils.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      copying grizli/galfit/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      copying grizli/galfit/psf.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      copying grizli/galfit/galfit.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      copying grizli/galfit/deconvolve.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/galfit
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/db.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/aws_drizzler.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/tile_mosaic.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/lambda_handler.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/field_tiles.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/visit_processor.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      copying grizli/aws/fit_redshift_lambda.py -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/aws
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/jwst_bp_info.yml -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/wfc3ir_ee.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCB1.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCB3.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/db.yml -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/visit_alignment.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCA4.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCB2.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/db.local.yml -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCALONG.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCA1.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/sep_catalog_junk.pkl -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/wfc3ir_dark_badpix_2019.01.12.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCA2.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/auto_script_defaults.yml -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCB4.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/gaia_dr2_vizier_columns.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/wfc3ir_badpix_spars200_22.03.31.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/hst_encircled_energy.fits -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCA3.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      copying grizli/data/nrc_lowpix_0916_NRCBLONG.fits.gz -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/selsing2016_quasar.vot -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/post_starburst.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/fsps_starburst_lines.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/quasar_lines.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/erb2010.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/cvd12_t11_solar_Chabrier.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/README -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/fsps_mature_lines.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/red_blue_continuum.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/eazy_intermediate.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/erb2010_continuum.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/red_blue_continuum_noLya.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/FeII_VeronCetty2004.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      copying grizli/data/templates/alf_SSP.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/L3.5.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/bt-settl_t400-3500_z0.0.fits -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/bt-settl_t400-7000_g4.5.fits -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/L1.0.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/M8.0.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/carbon_star.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/T7.5.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/L6.0.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/T6.0.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/T2.0.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/stars_settl.param -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/bt-settl_t400-5000_g4.5.fits -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      copying grizli/data/templates/stars/M6.5.txt -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/stars
      creating build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_008.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_009.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_009.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_008.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines.param -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_002.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3.param -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_012.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_006.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_007.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_003.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_001.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_005.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_011.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_010.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_004.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_004.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_010.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_001.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_011.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_005.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_007.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3.param.fits -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_003.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_002.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_006.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      copying grizli/data/templates/fsps/fsps_QSF_12_v3_nolines_012.dat -> build/lib.macosx-10.9-x86_64-cpython-310/grizli/data/templates/fsps
      running build_ext
      building 'grizli.utils_c.interp' extension
      creating build/temp.macosx-10.9-x86_64-cpython-310
      creating build/temp.macosx-10.9-x86_64-cpython-310/grizli
      creating build/temp.macosx-10.9-x86_64-cpython-310/grizli/utils_c
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/momcheva/miniconda3/envs/ahw2022/include -fPIC -O2 -isystem /Users/momcheva/miniconda3/envs/ahw2022/include -I/usr/local/opt/ruby@2.7/include -I/Users/momcheva/miniconda3/envs/ahw2022/include/python3.10 -c grizli/utils_c/interp.c -o build/temp.macosx-10.9-x86_64-cpython-310/grizli/utils_c/interp.o
      grizli/utils_c/interp.c:712:10: fatal error: 'numpy/arrayobject.h' file not found
      #include "numpy/arrayobject.h"
               ^~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grizli
  Running setup.py clean for grizli
  Building wheel for mastquery (setup.py) ... done
  Created wheel for mastquery: filename=mastquery-1.4-py3-none-any.whl size=44386 sha256=4df995c519fb27d57f0664e1b6bb665c1886d48c27090e62938980fa5666bc0b
  Stored in directory: /Users/momcheva/Library/Caches/pip/wheels/e2/ed/73/bc004fc88e9bed228ace26bd228429b809a3d53e55fc0f9c7a
  Building wheel for sregion (setup.py) ... done
  Created wheel for sregion: filename=sregion-1.0-py3-none-any.whl size=6966 sha256=7df0d0b981b32ae65ffaa818ae442430f3d5a43c5ec80548f89d1652aa01c58f
  Stored in directory: /Users/momcheva/Library/Caches/pip/wheels/41/bd/28/98f62f4dbd7e8a14170284ac26557452832fa95672d1d2b0d7
Successfully built mastquery sregion
Failed to build grizli
Installing collected packages: mastquery, six, shapely, PyYAML, pyparsing, pillow, numpy, kiwisolver, fonttools, cython, cycler, python-dateutil, pyerfa, packaging, contourpy, matplotlib, astropy, descartes, sregion, grizli
  Running setup.py install for grizli ... done
  DEPRECATION: grizli was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
Successfully installed PyYAML-6.0 astropy-5.1 contourpy-1.0.5 cycler-0.11.0 cython-0.29.32 descartes-1.1.0 fonttools-4.37.4 grizli-1.6.0 kiwisolver-1.4.4 mastquery-1.4 matplotlib-3.6.1 numpy-1.23.4 packaging-21.3 pillow-9.2.0 pyerfa-2.0.0.1 pyparsing-3.0.9 python-dateutil-2.8.2 shapely-1.8.5.post1 six-1.16.0 sregion-1.0
(ahw2022) momcheva@mac-n-152 ~ %

**Comment by BSGalvan** [comment]
I think I have figured out why this build error occurs.

I was also facing the same error with `gcc`, and the way to fix this error is to install `cython` and `numpy` _while_ creating the `conda` environment.

So we do:
- `conda create -n grizli-pip-test python=3.9 cython numpy pip`
- `conda activate grizli-pip-test`
- `pip install grizli` (this should now work!); you may also want to `pip cache purge` to do a clean reinstall...

To solve this issue in general (i.e. without invoking `conda`), I think the [general recommendation](https://peps.python.org/pep-0518/) is to specify these build-dependencies (`numpy`, `cython` etc.) into a `pyproject.toml` file instead of having them in `setup.py` or `setup.cfg`. This way `pip` knows to install these build-dependencies _before_ starting the `grizli` setup.

**Comment by jdavies-st** [comment]
Resolved by #6
