### ISSUE TITLE
All the requirements

### ISSUE THREAD

**Issue by ivastar** [ivastar/grizli#5]
From enviroment.yaml:

```
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- pip
- astropy
- scipy
- matplotlib
- scikit-image
- scikit-learn
- pyyaml
- cython
- photutils
- astroquery
- pyregion
- stsci.image
- stwcs
- hstcal
- wfc3tools
- crds
- drizzlepac
- shapely
- boto3
- tqdm
- pip:
  - astro-sedpy
  - astro-prospector
  - sep
  - peakutils
  - extinction
  - descartes
  - git+https://github.com/gbrammer/reprocess_wfc3.git
  - git+https://github.com/gbrammer/eazy-py.git
  - git+https://github.com/gbrammer/tristars.git
  - git+https://github.com/gbrammer/sregion.git
  - git+https://github.com/gbrammer/mastquery.git
```

**Comment by ivastar** [comment]
From requirements.txt

```
astropy
scipy
matplotlib
scikit-image
scikit-learn

pyyaml
cython

# photutils<1.1 needed for drizzlepac==3.2.1
#photutils==1.0.2
photutils
astroquery
pyregion

# explicit version for gh actions (2.3.5 was causing problems)
#stsci.image==2.3.3
stsci.image

stwcs
# hstcal (only works with conda)
wfc3tools
crds
drizzlepac

shapely
# descartes
git+https://github.com/benjimin/descartes.git
boto3
peakutils
extinction

tqdm

# Needed for template smoothing, doesn't bring whole fsps distro
astro-sedpy
astro-prospector

sep
# git+https://github.com/gbrammer/sep.git

# coord routines work without pyia
#git+https://github.com/gbrammer/pyia.git

git+https://github.com/gbrammer/reprocess_wfc3.git
git+https://github.com/gbrammer/eazy-py.git
# git+https://github.com/gbrammer/sregion.git
sregion>=1.0
git+https://github.com/gbrammer/tristars.git
# git+https://github.com/gbrammer/mastquery.git
mastquery>=1.4
```

**Comment by ivastar** [comment]
From instructions:

```
pip 
numpy 
cython
hstcal
pytest
eazy-py
awscli
boto3
git clone https://github.com/cmccully/lacosmicx.git
```

**Comment by ivastar** [comment]
Combined list of all the requirements:


```
- pip
- astropy
- scipy
- matplotlib
- scikit-image
- scikit-learn
- pyyaml
- cython
- photutils
- astroquery
- pyregion
- stsci.image
- stwcs
- hstcal
- wfc3tools
- crds
- drizzlepac
- shapely
- boto3
- tqdm
- pip:
  - astro-sedpy
  - astro-prospector
  - sep
  - peakutils
  - extinction
  - descartes
  - git+https://github.com/gbrammer/reprocess_wfc3.git
  - git+https://github.com/gbrammer/eazy-py.git
  - git+https://github.com/gbrammer/tristars.git
  - git+https://github.com/gbrammer/sregion.git / sregion>=1.0
  - git+https://github.com/gbrammer/mastquery.git / mastquery>=1.4
  - git+https://github.com/gbrammer/pyia.git?

awscli
boto3
git clone https://github.com/cmccully/lacosmicx.git
```

**Comment by BSGalvan** [comment]
Combined list of requirements, grouped by requirement:

# Build Requirements
These will go into `pyproject.toml` (along with `setuptools` & `wheel`; if #6 is merged)

```
- cython
- numpy
```

# Runtime Requirements

```
- astropy
- astroquery
- crds
- drizzlepac
- hstcal
- mastquery>=1.4
- matplotlib
- numpy
- photutils
- pip
- pyregion
- pyyaml
- scikit-image
- scikit-learn
- scipy
- shapely
- stsci.image
- stwcs
- tqdm
- wfc3tools
- pip:
  - astro-prospector
  - astro-sedpy
  - descartes
  - extinction
  - mastquery >=1.4
  - peakutils
  - sep
  - sregion >=1.0
  - git+https://github.com/gbrammer/reprocess_wfc3.git
  - git+https://github.com/gbrammer/eazy-py.git
  - git+https://github.com/gbrammer/tristars.git
  - git+https://github.com/cmccully/lacosmicx.git
```
Note: `descartes`, `extinction`, `peakutils` and `sep` have their latest PyPI versions also on `conda-forge` (which builds directly from PyPI). If we want, we can install them with `conda` instead of with `pip`, though to the end user it will make no difference!

# Additionals
We may add these under `[options.extras_require]`, with `test` and `hst` keys.

## Testing

```
- pytest
```

## AWS
If full HST pipeline reduction is desired.

```
- awscli
- boto3
```

**Comment by jdavies-st** [comment]
Agree that having extras such as `test`, `aws`, `hst` and `jwst` would be excellent.

Further, we can eventually fix the github action that checks the build to use modern tools as well, as now that the build dependencies are in pyproject.toml, there's no need to install them in the github workflow.

https://github.com/ivastar/grizli/blob/f9e764b97954cff55b5714869f8a07ab5abad700/.github/workflows/python-package.yml#L30-L39

**Comment by jdavies-st** [comment]
It would also be good to just remove requirements.txt completely so we're keeping track of dependencies in one place and one place only.  If we wanted to make an `[all]` extra to capture the requirements.txt, that would be fine too I think.

By keeping all requirements in setup, then the install instructions are very simple for all the use cases:

```
pip install grizli[all]
```
or
```
pip install grizli[hst,aws]
pip install grizli[jwst,test]
```
etc.

**Comment by jdavies-st** [comment]
Finally we should always prefer installing from pypi instead of conda, unless there's a really strong reason not to (i.e. a binary is needed and the package is not maintained well (doesn't install easily if compile is needed).  I don't think this the case for any of these dependencies though.  This keeps installation simple, as above.  And it avoids having conflicts amongst pip and conda package installations.

**Comment by ivastar** [comment]
Done.
